Make sure Parameters Expressions are string when saving custom styles
plone/plone.app.theming pull request #210
Opened 2022-07-29 17:46 UTC by frapell

This PR fixes gh-209

2022-07-29 17:46 UTC, mister-roboto commented
@frapell thanks for creating this Pull Request and helping to improve Plone!

TL;DR: Finish pushing changes, pass all other checks, then paste a comment:
```
@jenkins-plone-org please run jobs
```

To ensure that these changes do not break other parts of Plone, the Plone test suite matrix needs to pass, but it takes 30-60 min.  Other CI checks are usually much faster and the Plone Jenkins resources are limited, so when done pushing changes and all other checks pass either [start all Jenkins PR jobs yourself](https://jenkinsploneorg.readthedocs.io/en/latest/run-pull-request-jobs.html#run-a-pull-request-job), or simply add the comment above in this PR to start all the jobs automatically.

Happy hacking!

2022-07-29 17:46 UTC, frapell commented
@jenkins-plone-org please run jobs

2022-08-24 22:36 UTC, mauritsvanrees requested changes
It works, and should be fine, but I don't completely trust it on Python 2. See inline comment.

A bit related is https://github.com/plone/Products.CMFPlone/issues/1759 which I saw today. Lesson from there is that currently `parameterExpressions` keys and values must be ASCII.

2022-08-24 22:36 UTC, mauritsvanrees commented on src/plone/app/theming/browser/controlpanel.py
> +                    if isinstance(line, six.binary_type):
I have tried this on standard Plone 5.2 on Py 2 and 3. The change works. But I don't completely trust it for Python 2. If the line is binary, you decode it to unicode, but afterwards the code calls `str` on it, making it binary again. In fact when I try it in Python 2, the line is already unicode, so this change has no effect. But I still don't trust it. Please do this on Python 3 only:

```suggestion
                    if six.PY3 and isinstance(line, six.binary_type):
```

2022-08-25 12:23 UTC, frapell commented
@mauritsvanrees Thank you for your suggestion, applied.

@jenkins-plone-org please run jobs

2022-08-25 13:02 UTC, mauritsvanrees approved these changes

2022-08-25 13:28 UTC, merged